music_app/config/routes.rb
Rails.application.routes.draw do
  
resources :users, only: [:new, :create, :show ]
resource :session, only: [:new, :create, :destroy ]

end

music_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

music_app/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint           not null, primary key
#  email           :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#


class User < ApplicationRecord
  
  validates :email, :session_token, presence: true, uniqueness: true
  validates :password_digest, presence: true
  validates :password, length: {minimum: 6}, allow_nil: true
  
  after_initialize :ensure_session_token
  
  attr_reader :password

  def self.find_by_credentials(email, password)
    @user = User.find_by(email: email)
    return nil unless @user && @user.is_password?(password)
    @user
  end

  def self.generate_session_token
    SecureRandom::urlsafe_base64
  end

  def reset_session_token!
    self.session_token = User.generate_session_token
    self.save!
    self.session_token
  end


  def ensure_session_token
    self.session_token ||= User.generate_session_token
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    bcrypt_password = BCrypt::Password.new(self.password_digest)
    bcrypt_password.is_password?(password)
  end

end

music_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  skip_before_action :verify_authenticity_token

  helper_method :current_user, :logged_in?

  def current_user
    return nil unless session[:session_token]
    User.find_by(session_token: session[:session_token])
  end

  def logged_in?
    !!current_user
  end

  def log_in_user!(user)
    session[:session_token] = user.reset_session_token!
  end

end

music_app/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    debugger
    render :new
  end

  def create
    user = User.find_by_credentials(
      params[:email],
      params[:password]
      )
      debugger
      
      if user.save
        log_in_user!(user)
        redirect_to user_url(user)
      else  
        render :new, status: 401
      end
  end

  def destroy
    current_user.reset_session_token!
    session[:session_token] = nil #user.session_token = nil 
    redirect_to new_user_url #ADD IN MUSIC#INDEX HOME PAGE LATER
  end

end

music_app/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      log_in_user!(@user)
      redirect_to user_url(@user)# CHANGE LATER ???
    else
      render :new, status: 422
    end
  end

  def show
    @user = User.find(params[:id]) #use find usually with wildcard (hardcoded id)

    render :show # add stuff to view
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end

end

music_app/app/helpers/application_helper.rb
module ApplicationHelper
end

music_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <% if logged_in? %>
      Current user email: <%= current_user.email %>
      <form action="<%= session_url %>" method="POST">
        <input type="hidden" name="_method" value="DELETE">
        <input type="submit" value="Log out!">
      </form>
    <% elsif params[:controller] != 'sessions' %>
      <a href="<%= new_session_url %>">Log in!</a>
    <% end %>

    <%= yield %>
  </body>
</html>

music_app/app/views/users/new.html.erb
<h1>Create Your User</h1>

<form action="<%= users_url %>" method="POST">

  <ul>
  <% @user.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
  </ul>

  <label for="user_email">Email:</label>
  <input type="email" name="user[email]" id="user_email" value="<%= @user.email %>">

  <br>

  <label for="user_password">Password:</label>
  <input type="password" name="user[password]" id="user_password">

  <br>

  <input type="submit" value="Create User">

</form>

music_app/app/views/users/show.html.erb
<h1><%= @user.email %></h1>